fix loading config from pubspec.yaml
fluttercommunity/flutter_launcher_icons pull request #398
Opened 2022-08-02 18:15 UTC by p-mazhnik

2022-08-02 18:24 UTC, p-mazhnik commented
Actually I don't like current solution (and it even breaks tests).
Probably we shouldn't have default value for the `-f` flag, or we should fix the tests and let `pubspec.yml` to be a fallback, if config provided using `-f` flag is not exists

2022-08-03 08:06 UTC, RatakondalaArun commented
@p-mazhnik @MarkOSullivan94 

Instead of using `loadConfigFileFromArgResults()` we can use [`FlutterLauncherIconsConfig#toJson()`](https://github.com/fluttercommunity/flutter_launcher_icons/blob/master/lib/flutter_launcher_icons_config.dart#L134-L136) instance method to get already loaded configs

- This prevents us from loading configs twice
- Fallback to `pubspec.yaml` is already included

https://github.com/fluttercommunity/flutter_launcher_icons/blob/4ffd0f544af0b1accaafc686fe392b365b9b43b4/lib/main.dart#L77-L79

2022-08-03 08:53 UTC, p-mazhnik commented
@RatakondalaArun I can try to refactor this in the current PR

2022-08-03 10:21 UTC, MarkOSullivan94 commented
Converting this to draft until changes are made

2022-08-03 10:39 UTC, p-mazhnik commented
@RatakondalaArun I couldn't just use `FlutterLauncherIconsConfig#toJson()` because result will always contain all keys, but we had functions like `hasAndroidConfig` that are checked for the keys existence. So I refactored the code to use `FlutterLauncherIconsConfig` instead of `Map<String, dynamic>`

2022-08-03 14:39 UTC, RatakondalaArun commented
@p-mazhnik 
I think there is no need for so many changes

1.`createIconsFromArguments()`: Is the entry point. This is where parsing and loading configs happen
2.`createIconsFromConfig()`: Is responsible for checking config to see if configs are present or not (i.e: `hasAndroidConfig` will go inside this function)

Below are the changes that are required prefixed with (👇)
```dart
final ArgResults argResults = parser.parse(arguments);
  // creating logger based on -v flag
  final logger = FLILogger(argResults[verboseFlag]);
  // 👇 Move this to here
  final String prefixPath = argResults[prefixOption]; 

  logger.verbose('Received args ${argResults.arguments}');

  if (argResults[helpFlag]) {
    stdout.writeln('Generates icons for iOS and Android');
    stdout.writeln(parser.usage);
    exit(0);
  }

  // Flavors management
  final flavors = getFlavors();
  final hasFlavors = flavors.isNotEmpty;

  // Load configs from given file(defaults to ./flutter_launcher_icons.yaml) or from ./pubspec.yaml
  final flutterLauncherIconsConfigs =
      FlutterLauncherIconsConfig.loadConfigFromPath(argResults[fileOption], prefixPath) ??
          FlutterLauncherIconsConfig.loadConfigFromPubSpec(prefixPath);

 // 👇 Update this to only check for flutterLauncherIconsConfigs
  if (flutterLauncherIconsConfigs == null) {
    throw NoConfigFoundException(
      'No configuration found in $defaultConfigFile or in ${constants.pubspecFilePath}. '
      'In case file exists in different directory use --file option',
    );
  }

  // 👇 Instead of using loadConfigFileFromArgResults use flutterLauncherIconsConfigs#toJson
  // Load the config file
  final Map<String, dynamic> yamlConfig = flutterLauncherIconsConfigs.toJson(); //loadConfigFileFromArgResults(argResults, verbose: true);
```
@MarkOSullivan94 correct me if I am wrong

2022-08-03 15:02 UTC, p-mazhnik commented
@RatakondalaArun 
problem here is that after you will pass new `yamlConfig` into `createIconsFromConfig` function, all the checks won't work as expected, such as `isImagePathInConfig`, `hasPlatformConfig`, `isNeedingNewAndroidIcon`, etc. 
Because `flutterLauncherIconsConfigs.toJson()` will return Map that will contain all the keys, so code like `flutterLauncherIconsConfig.containsKey('ios')` always will return `true`. That's why I made this refactoring.

2022-08-03 16:29 UTC, RatakondalaArun commented on test/android_test.dart
> +      false,
```suggestion
      isTrue,
```

2022-08-03 16:30 UTC, RatakondalaArun commented on test/android_test.dart
> +      true,
```suggestion
      isTrue,
```

2022-08-03 16:31 UTC, RatakondalaArun commented on test/android_test.dart
> +      'assets/images/icon-android.png',
```suggestion
      equals('assets/images/icon-android.png'),
```

2022-08-03 16:32 UTC, RatakondalaArun commented on test/flutter_launcher_icons_config_test.dart
> +        expect(configs!.imagePath, imagePath);
```suggestion
        expect(configs!.imagePath, equals(imagePath));
```

2022-08-03 16:32 UTC, RatakondalaArun commented on test/main_test.dart
> +      expect(config!.android, true);
```suggestion
      expect(config!.android, isTrue);
```

2022-08-03 16:33 UTC, RatakondalaArun commented on test/main_test.dart
> +      expect(config!.ios, false);
```suggestion
      expect(config!.ios, isFalse);
```

2022-08-03 16:33 UTC, RatakondalaArun commented on test/main_test.dart
> +      expect(config!.ios, true);
```suggestion
      expect(config!.ios, isTrue);
```

2022-08-03 16:34 UTC, RatakondalaArun commented on test/main_test.dart
> +    expect(config.getImagePathAndroid(), 'assets/images/icon-710x599.png');
```suggestion
    expect(config.getImagePathAndroid(), equals('assets/images/icon-710x599.png'));
```

2022-08-03 16:34 UTC, RatakondalaArun commented on test/main_test.dart
> +    expect(configAndroid.getImagePathAndroid(), 'assets/images/icon-710x599.png');
```suggestion
    expect(configAndroid.getImagePathAndroid(), equals('assets/images/icon-710x599.png'));
```

2022-08-03 16:35 UTC, RatakondalaArun commented on test/main_test.dart
> +    expect(configBoth.getImagePathAndroid(), 'assets/images/icon-android.png');
```suggestion
    expect(configBoth.getImagePathAndroid(), equals('assets/images/icon-android.png'));
```

2022-08-03 16:35 UTC, RatakondalaArun commented on test/main_test.dart
> +    expect(config.hasPlatformConfig, true);
```suggestion
    expect(config.hasPlatformConfig, isTrue);
```

2022-08-03 16:35 UTC, RatakondalaArun commented on test/main_test.dart
> +    expect(config.hasPlatformConfig, false);
```suggestion
    expect(config.hasPlatformConfig, isFalse);
```

2022-08-03 16:36 UTC, RatakondalaArun commented on test/main_test.dart
> +    expect(config.isNeedingNewAndroidIcon, false);
```suggestion
    expect(config.isNeedingNewAndroidIcon, isFalse);
```

2022-08-03 16:36 UTC, RatakondalaArun commented on test/main_test.dart
> +    expect(config.isNeedingNewAndroidIcon, false);
```suggestion
    expect(config.isNeedingNewAndroidIcon, isFalse);
```

2022-08-03 16:36 UTC, RatakondalaArun commented on test/main_test.dart
> +    expect(config.isNeedingNewIOSIcon, false);
```suggestion
    expect(config.isNeedingNewIOSIcon, isFalse);
```

2022-08-03 16:41 UTC, RatakondalaArun requested changes
Few changes in tests

2022-08-04 11:16 UTC, RatakondalaArun approved these changes
LGTM

2022-08-04 15:19 UTC, merged