related to [issue #96], Suggestion for an easier way to apply foreground inset
fluttercommunity/flutter_launcher_icons pull request #563
Opened 2024-06-12 01:40 UTC by LOCKEDFILE

I requested a PR for those who find it bothersome to change it manually every time. The default value for the inset is 16.

how to use:
~~~yaml
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon/icon.png"
  adaptive_icon_background: "assets/app_icon/adaptive_icon_background.png"
  adaptive_icon_foreground: "assets/app_icon/adaptive_icon_foreground.png"
  adaptive_icon_foreground_inser: 16  # default value is 16
~~~

before:
~~~xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@drawable/ic_launcher_background"/>
  <foreground android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
~~~

after:
~~~xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@drawable/ic_launcher_background"/>
  <foreground>
    <inset
      android:drawable="@drawable/ic_launcher_foreground"
      android:inset="16%" />
  </foreground>
</adaptive-icon>
~~~

2024-09-01 23:22 UTC, martinbutt commented
Just tested this and it works perfectly.

2024-09-09 19:23 UTC, MarkOSullivan94 commented on lib/android.dart
> +        '  <foreground>\n    <inset\n      android:drawable="@drawable/ic_launcher_foreground"\n      android:inset="${config.adaptiveIconForegroundInset}%" />\n  </foreground>\n';
This is far too wide

Turn this into a multi-line string and have a line break after each `\n`

2024-09-09 19:23 UTC, MarkOSullivan94 commented on lib/android.dart
You're missing the same configuration for monochrome icons

2024-09-09 19:24 UTC, MarkOSullivan94 requested changes
I tried this out and it's working for normal icons but not for monochrome icons

Add the same functionality for monochrome icons and fix the styling so it's not too wide on one line

2024-09-09 19:25 UTC, MarkOSullivan94 commented
Thank you for your contribution @LOCKEDFILE and thank you for testing @martinbutt

2024-09-10 04:03 UTC, LOCKEDFILE commented
@MarkOSullivan94,  thanks you for your comments.

i fixed monochorome insets and multi line styling.

2024-09-21 15:27 UTC, MarkOSullivan94 approved these changes
I've tested this out and it's working as expected

**flutter_launcher_icons v0.13.1**

<img src="https://github.com/user-attachments/assets/ce16287d-1394-4404-b056-8308f0a69f07" width=50%>

**This PR**

<img src="https://github.com/user-attachments/assets/a420fefd-28b0-4eb9-8fd0-2e03068d3d83" width=50%>

These screenshots were taken on Pixel 8 Pro emulator with API VanillaIceCream

2024-09-21 15:28 UTC, MarkOSullivan94 commented
Thanks for making the requested changes @LOCKEDFILE

2024-09-21 15:29 UTC, merged